// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1WTg33B45GKyU1o6imYrqhA1eI5RpB0',
    appId: '1:765044191222:web:71f9798fee13a9dea321d7',
    messagingSenderId: '765044191222',
    projectId: 'recipe-45b98',
    authDomain: 'recipe-45b98.firebaseapp.com',
    databaseURL: 'https://recipe-45b98-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-45b98.appspot.com',
    measurementId: 'G-BDZL8HV6PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs0FyprZ-8_9YUbYKo2Knn9uBS9i5RHIM',
    appId: '1:765044191222:android:5d60913cd9d99abaa321d7',
    messagingSenderId: '765044191222',
    projectId: 'recipe-45b98',
    databaseURL: 'https://recipe-45b98-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-45b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIHCpg7QeCsGVay8nurldkyoJ5WIimTBk',
    appId: '1:765044191222:ios:2cd405377ee8a05ea321d7',
    messagingSenderId: '765044191222',
    projectId: 'recipe-45b98',
    databaseURL: 'https://recipe-45b98-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-45b98.appspot.com',
    iosClientId: '765044191222-1eadbd2tqp00b5e84ad87hsqmnfmjfoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIHCpg7QeCsGVay8nurldkyoJ5WIimTBk',
    appId: '1:765044191222:ios:2cd405377ee8a05ea321d7',
    messagingSenderId: '765044191222',
    projectId: 'recipe-45b98',
    databaseURL: 'https://recipe-45b98-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-45b98.appspot.com',
    iosClientId: '765044191222-1eadbd2tqp00b5e84ad87hsqmnfmjfoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipe',
  );
}
